apiVersion: v1
kind: Service
metadata:
  name: test-service-service
  namespace: test-service
  labels:
    app: test-service
spec:
  type: LoadBalancer
  selector:
    app: test-service
  ports:
    - protocol: TCP
      port: 9082
      targetPort: 9082
